export const POKEMON_DATA_FETCH = "POKEMON_DATA_FETCH";
export const POKEMON_DATA_FETCH_SUCCESS = "POKEMON_DATA_FETCH_SUCCESS";
export const POKEMON_DATA_FETCH_FAILURE = "POKEMON_DATA_FETCH_FAILURE";
